# Generated by Django 2.2.7 on 2019-11-15 08:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0006_auto_20191115_0513'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserImageInfo',
            new_name='Profile',
        ),
    ]
